/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE LOG PACKING
package com.MAVLink.daedalus;
import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;
        
/**
 *  Contains log data of the Seed
 */
public class msg_log extends MAVLinkMessage {

    public static final int MAVLINK_MSG_ID_LOG = 88552;
    public static final int MAVLINK_MSG_LENGTH = 255;
    private static final long serialVersionUID = MAVLINK_MSG_ID_LOG;

      
    /**
     * Seed local time
     */
    public long time_local;
      
    /**
     * system time
     */
    public long d2time;
      
    /**
     * Logging data
     */
    public byte log_msg[] = new byte[243];
    

    /**
     * Generates the payload for a mavlink message for a message of this type
     * @return
     */
    @Override
    public MAVLinkPacket pack() {
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH,isMavlink2);
        packet.sysid = 255;
        packet.compid = 190;
        packet.msgid = MAVLINK_MSG_ID_LOG;
        
        packet.payload.putLong(time_local);
        packet.payload.putUnsignedInt(d2time);
        
        for (int i = 0; i < log_msg.length; i++) {
            packet.payload.putByte(log_msg[i]);
        }
                    
        
        if (isMavlink2) {
            
        }
        return packet;
    }

    /**
     * Decode a log message into this class fields
     *
     * @param payload The message to decode
     */
    @Override
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();
        
        this.time_local = payload.getLong();
        this.d2time = payload.getUnsignedInt();
         
        for (int i = 0; i < this.log_msg.length; i++) {
            this.log_msg[i] = payload.getByte();
        }
                
        
        if (isMavlink2) {
            
        }
    }

    /**
     * Constructor for a new message, just initializes the msgid
     */
    public msg_log() {
        this.msgid = MAVLINK_MSG_ID_LOG;
    }
    
    /**
     * Constructor for a new message, initializes msgid and all payload variables
     */
    public msg_log( long time_local, long d2time, byte[] log_msg) {
        this.msgid = MAVLINK_MSG_ID_LOG;

        this.time_local = time_local;
        this.d2time = d2time;
        this.log_msg = log_msg;
        
    }
    
    /**
     * Constructor for a new message, initializes everything
     */
    public msg_log( long time_local, long d2time, byte[] log_msg, int sysid, int compid, boolean isMavlink2) {
        this.msgid = MAVLINK_MSG_ID_LOG;
        this.sysid = sysid;
        this.compid = compid;
        this.isMavlink2 = isMavlink2;

        this.time_local = time_local;
        this.d2time = d2time;
        this.log_msg = log_msg;
        
    }

    /**
     * Constructor for a new message, initializes the message with the payload
     * from a mavlink packet
     *
     */
    public msg_log(MAVLinkPacket mavLinkPacket) {
        this.msgid = MAVLINK_MSG_ID_LOG;
        
        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.isMavlink2 = mavLinkPacket.isMavlink2;
        unpack(mavLinkPacket.payload);
    }

         
    /**
    * Sets the buffer of this message with a string, adds the necessary padding
    */
    public void setLog_Msg(String str) {
        int len = Math.min(str.length(), 243);
        for (int i=0; i<len; i++) {
            log_msg[i] = (byte) str.charAt(i);
        }

        for (int i=len; i<243; i++) {            // padding for the rest of the buffer
            log_msg[i] = 0;
        }
    }

    /**
    * Gets the message, formated as a string
    */
    public String getLog_Msg() {
        StringBuffer buf = new StringBuffer();
        for (int i = 0; i < 243; i++) {
            if (log_msg[i] != 0)
                buf.append((char) log_msg[i]);
            else
                break;
        }
        return buf.toString();

    }
                         
    /**
     * Returns a string with the MSG name and data
     */
    @Override
    public String toString() {
        return "MAVLINK_MSG_ID_LOG - sysid:"+sysid+" compid:"+compid+" time_local:"+time_local+" d2time:"+d2time+" log_msg:"+log_msg+"";
    }
    
    /**
     * Returns a human-readable string of the name of the message
     */
    @Override
    public String name() {
        return "MAVLINK_MSG_ID_LOG";
    }
}
        