package de.wuespace.telestion.project.daedalus2.mavlink;
import de.wuespace.telestion.extension.mavlink.annotation.MavField;
import de.wuespace.telestion.extension.mavlink.annotation.MavInfo;
import de.wuespace.telestion.extension.mavlink.annotation.NativeType;
import de.wuespace.telestion.extension.mavlink.annotation.MavArray;
import de.wuespace.telestion.extension.mavlink.message.MavlinkMessage;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * Freetext command input, one command per message.<br>
 * <br>
 * <i>Autogenerated by XML2Record-Tool v1.3.11</i>
 * 
 * @author Autogenerated by XML2Record-Tool (by Cedric Boes)
 * @version 1.0 (autogenerated)
 */
@MavInfo(id = 10004, crc = 124)
public record ConCmd(
	/**
	 * CMD content<br>
	 * <br>
	 * <i>Autogenerated by XML2Record-Tool v1.3.11</i>
	 */
	@MavArray(length = 255)
	@MavField(nativeType = NativeType.CHAR)
	@JsonProperty char[] conCmd) implements MavlinkMessage {
	/**
	 * There shall be no default-constructor for normal developers.
	 */
	@SuppressWarnings("unused")
	private ConCmd() {
		this(null);
	}
}