package de.wuespace.telestion.project.daedalus2.mavlink;

import de.wuespace.telestion.extension.mavlink.annotation.MavField;
import de.wuespace.telestion.extension.mavlink.annotation.MavInfo;
import de.wuespace.telestion.extension.mavlink.NativeType;
import de.wuespace.telestion.extension.mavlink.message.MavlinkMessage;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 *  Contains information about the current state and local time.<br>
 * <br>
 * <i>Autogenerated by XML2Record-Tool v1.3.12</i>
 * 
 * @author Autogenerated by XML2Record-Tool (by Cedric Boes)
 * @version 1.0 (autogenerated)
 */
@MavInfo(id = 10001, crc = 17)
@SuppressWarnings("preview")
public record SeedHeartbeat(
	/**
	 * Seed local time<br>
	 * <br>
	 * <i>Autogenerated by XML2Record-Tool v1.3.12</i>
	 */
	@MavField(nativeType = NativeType.INT_64)
	@JsonProperty long timeLocal, 
	/**
	 * current System state<br>
	 * <br>
	 * <i>Autogenerated by XML2Record-Tool v1.3.12</i>
	 */
	@MavField(nativeType = NativeType.UINT_8)
	@JsonProperty int stateCur) implements MavlinkMessage {
	/**
	 * There shall be no default-constructor for normal developers.
	 */
	@SuppressWarnings("unused")
	private SeedHeartbeat() {
		this(0, 0);
	}
}