#!/usr/bin/env bash

set -e

# Telestion executable for managing the docker containers
# which contain the application and database.
# By WüSpace e. V. (c) 2021

COMPOSE_FILE="docker-compose.yml"
COMPOSE_PROFILE="prod"
PWD="$(pwd)"

EXIT_ERROR=1

error() {
    echo -e "\e[1;31mERROR:\e[1;37m $1\e[0m"
}

# final checks
if ! [ -f "$PWD/$COMPOSE_FILE" ]; then
    error "$COMPOSE_FILE not found"
    exit $EXIT_ERROR
fi

if ! command -v "docker-compose" &> /dev/null; then
    error "docker-compose not found. Did you install it?"
    exit $EXIT_ERROR
fi

# mock docker-compose lol
sudo docker-compose --file "$PWD/$COMPOSE_FILE" --profile "$COMPOSE_PROFILE" "$@"
