# For most projects, this workflow file will not need changing; you simply need
# to commit it to your repository.
#
# ******** NOTE ********
# If you need access to the GitHub Maven package registry from other repositories,
# create a personal access token with the following scopes:
# - read:packages
# and name it "READ_PACKAGES".
# After this step, overwrite the default GITHUB_TOKEN environment variable with the created PAT
# in the gradle build and test steps.
name: CI application

# Events that trigger this workflow
on: [push, pull_request]

jobs:
  build:
    name: Build packages
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./application
    steps:
      - name: Checkout 📥
        uses: actions/checkout@v2.3.4
        with:
          submodules: true

      - name: Restore gradle cache ♻️
        uses: actions/cache@v2.1.6
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: |
            ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK 16 💿
        uses: actions/setup-java@v2.1.0
        with:
          distribution: 'zulu'
          java-version: '16'
          java-package: jdk

      - name: Build packages 🛠️
        run: chmod +x gradlew && ./gradlew build
        env:
          GITHUB_TOKEN: ${{ secrets.READ_PACKAGES }}

  test:
    name: Test packages
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./application
    steps:
      - name: Checkout 📥
        uses: actions/checkout@v2.3.4
        with:
          submodules: true

      - name: Restore gradle cache ♻️
        uses: actions/cache@v2.1.6
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: |
            ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK 16 💿
        uses: actions/setup-java@v2.1.0
        with:
          distribution: 'zulu'
          java-version: '16'
          java-package: jdk

      - name: Build packages 🛠️
        run: chmod +x gradlew && ./gradlew build
        env:
          GITHUB_TOKEN: ${{ secrets.READ_PACKAGES }}

      - name: Test packages 🛃
        run: ./gradlew test
        env:
          GITHUB_TOKEN: ${{ secrets.READ_PACKAGES }}
