name: Publish setup

# Events that trigger this workflow
on:
  workflow_run:
    workflows: ["Release"]
    types: [completed]

jobs:
  publish-setup:
    name: Publish setup and configuration scripts
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout 📥
        uses: actions/checkout@v2.4.0
        with:
          submodules: true

      - name: Download build environment 📥
        uses: dawidd6/action-download-artifact@v2.16.0
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          workflow_conclusion: success
          name: build-env
          path: ${{ github.workspace }}

      - name: Import environment ⛓
        shell: bash
        run: cat "${GITHUB_WORKSPACE}/.build-env" >> $GITHUB_ENV

      - name: Fail on skipped release
        run: test "$SKIPPED" = "false"
        env:
          SKIPPED: ${{ env.skipped }}

      - name: Tag docker image in compose file
        run: |
          sed -i "s/${PLACEHOLDER}/${REPLACE_WITH}/g" application/production.yml
        env:
          PLACEHOLDER: "##TAG##"
          REPLACE_WITH: ${{ env.version }}

      - name: Copy required components ✂️
        run: |
          mkdir -p "${TEMP_DIR}/${BUILD_DIR}"
          cp -r application/{conf,data,production.yml} "${TEMP_DIR}/${BUILD_DIR}/"
          mv "${TEMP_DIR}/${BUILD_DIR}/production.yml" "${TEMP_DIR}/${BUILD_DIR}/docker-compose.yml"
        env:
          TEMP_DIR: ${{ runner.temp }}
          BUILD_DIR: telestion-project-daedalus2-${{ env.tag }}

      - name: Compress production workspace 📦
        working-directory: ${{ runner.temp }}
        run: zip -r "${BUILD_DIR}.zip" "${BUILD_DIR}"
        env:
          TEMP_DIR: ${{ runner.temp }}
          BUILD_DIR: telestion-project-daedalus2-${{ env.tag }}

      - name: Upload release workspace 🪡
        if: ${{ env.skipped == 'false' }}
        uses: svenstaro/upload-release-action@2.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.tag }}
          file: ${{ runner.temp }}/telestion-project-daedalus2-${{ env.tag }}.zip
