name: Publish Docker Image
on:
  release:
    types: [published]
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Build App
        run: chmod +x gradlew && ./gradlew assembleDist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          path: ./
          username: ${{ github.ACTOR }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          always_pull: true
          repository: ORGANIZATION_OR_USER_NAME/REPO_NAME/IMAGE_NAME
          cache_froms: ORGANIZATION_OR_USER_NAME/REPO_NAME/IMAGE_NAME:latest
          tags: latest
          tag_with_ref: true
  #        tag_with_sha: true
          add_git_labels: true

